Fix bugs in CI workflow.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -16,13 +16,14 @@ concurrency:
   cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
 
 jobs:
-  build:
+  run-tests:
+    name: Python ${{ matrix.python-version }}
 
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
+        python-version: ["3.9", "3.10", "3.11", "3.12"]
 
     steps:
 
@@ -64,27 +65,27 @@ jobs:
         if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
         run: poetry install --with dev
 
-    # --- Run tests
+      # --- Run tests
 
-    - name: Lint with flake8
-      run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # The GitHub editor is 127 chars wide and save output to variable
-        OUTPUT=$(flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics)
-        echo "$OUTPUT"
-        # Take last line of output
-        count=$(echo "$OUTPUT" | tail -1)
-        # Fail test explicitly if count >= 10
-        if [[ $count -ge 10 ]]; then exit $count; fi
+      - name: Lint with flake8
+        run: |
+          # stop the build if there are Python syntax errors or undefined names
+          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+          # The GitHub editor is 127 chars wide and save output to variable
+          OUTPUT=$(flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics)
+          echo "$OUTPUT"
+          # Take last line of output
+          count=$(echo "$OUTPUT" | tail -1)
+          # Fail test explicitly if count >= 10
+          if [[ $count -ge 10 ]]; then exit $count; fi
+  
+      - name: Setup env for tests
+        run: |
+          git config --global user.email "you@example.com"
+          git config --global user.name "Your Name"
 
-    - name: Setup env for tests
-      run: |
-        git config --global user.email "you@example.com"
-        git config --global user.name "Your Name"
-
-    - name: Run tests
-      run: |
-        source $VENV
-        export MAX_THRESHOLD_SIZE=10240
-        poetry run pytest --cov-report=xml
+      - name: Run tests
+        run: |
+          source $VENV
+          export MAX_THRESHOLD_SIZE=10240
+          poetry run pytest --cov-report=xml
